### PR TITLE
added mayurikolhe

### PR DESCRIPTION
**Pull request by MayuriKolhe-2003**
Please accept my PR for Hactoberfest.

### CODE REVIEW

**Comment by abhijitmondal121** [comment]
Plz stared the repo it's mandatory and you can also follow my profile.

**Comment by MayuriKolhe-2003** [comment]
Yes..i starred the repo and also followed you.

**Comment by abhijitmondal121** [comment]
Ok thank you.Happy hacking.

**Comment by MayuriKolhe-2003** [comment]
Can you please tag me hactoberfest accepted.

**Pull request merged**
