### PR TITLE
Profile Card

### PR DESCRIPTION
**Pull request by Imnitesh21**

### CODE REVIEW

**Comment by abhijitmondal121** [comment]
Star the repo this is mandatory and you can also follow me.

**Comment by Imnitesh21** [comment]
Done @abhijitmondal121

**Comment by Imnitesh21** [comment]
> Star the repo this is mandatory and you can also follow me.

Hello, @abhijitmondal121  I have done star the repo and followed you. please merge my files.

**Comment by abhijitmondal121** [comment]
Your pull request is conflicts. Plz make a new fork and pull request I will accept that.

**Pull request closed without merging**
